# Generated by Django 5.2.7 on 2025-10-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komutEkle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
